process.env.GMAIL_USER="t@gmail.com";process.env.GMAIL_APP_PASSWORD="abcd efgh ijkl mnop";
import nm from "nodemailer";const CODE=()=>/(\d{6})/.exec(nm.__sent.at(-1).text)[1];
process.env.ADMIN_EMAILS="admin@x.com";
import h from "./api.mjs";
let n=0,bad=0;const ok=(c,l)=>{n++;if(!c){bad++;console.log("FAIL",l)}};
const call=async(m,p,b,tok)=>{const r=await h(new Request("http://x/api"+p,{method:m,headers:{"content-type":"application/json",...(tok?{authorization:"Bearer "+tok}:{})},body:b?JSON.stringify(b):undefined}));return r.json()};
const login=async e=>{const o=await call("POST","/otp",{email:e});return (await call("POST","/verify",{email:e,code:CODE(),country:"NG"})).token};
const J="data:image/jpeg;base64,/9j/AAAA",fr=[J,J,J];
const A=await login("admin@x.com"),U1=await login("u1@x.com"),U2=await login("u2@x.com"),U3=await login("u3@x.com");
ok((await call("POST","/liveness",{frames:fr,hash:"ffff0000ffff0000",motion:9})).error?.includes("sign in"),"needs login");
ok((await call("POST","/liveness",{frames:fr,hash:"ffff0000ffff0000",motion:1},U1)).error?.includes("move"),"static photo rejected");
ok((await call("POST","/liveness",{frames:["x",J,J],hash:"ffff0000ffff0000",motion:9},U1)).error,"bad images rejected");
ok((await call("POST","/liveness",{frames:fr,hash:"zz",motion:9},U1)).error,"bad hash rejected");
let r=await call("POST","/liveness",{frames:fr,hash:"ffff0000ffff0000",motion:9,challenges:["left","smile","blink"]},U1);ok(r.ok&&r.status==="verified","first person verified");
ok((await call("GET","/liveness/me","",U1)).status==="verified","status readable");
r=await call("POST","/liveness",{frames:fr,hash:"ffff0000ffff0001",motion:9},U2);ok(r.ok&&r.status==="review","same face on 2nd account -> review");
r=await call("POST","/liveness",{frames:fr,hash:"0f0f0f0ff0f0f0f0",motion:9},U3);ok(r.status==="verified","different face verified");
ok((await call("POST","/offers",{provide:"USD",want:"NGN",rate:1500,min:1,max:9},U2)).error?.includes("review"),"flagged account can't publish offers");
ok((await call("POST","/offers",{provide:"USD",want:"NGN",rate:1500,min:1,max:9},U3)).ok,"verified account can publish");
ok((await call("GET","/liveness/flags","",U1)).error==="Admin access only.","flags admin-only");
const fl=(await call("GET","/liveness/flags","",A)).flags;ok(fl.length===1&&fl[0].email==="u2@x.com","admin sees flag");
ok((await call("POST","/liveness/clear",{email:"u2@x.com"},A)).ok,"admin clears");
ok((await call("POST","/offers",{provide:"EUR",want:"NGN",rate:1600,min:1,max:9},U2)).ok,"cleared account can publish");
r=await call("POST","/liveness",{frames:fr,hash:"1234567890abcdef",motion:0,fallback:true},(await login("selfie@x.com")));ok(r.status==="review","selfie fallback goes to review");
console.log(n+" checks, "+bad+" failed");
