process.env.DATABASE_URL="postgres://fake";process.env.ADMIN_EMAILS="admin@x.com";process.env.PAYSTACK_SECRET_KEY="";
import h from "./api.mjs";import pgm from "pg";
let n=0,bad=0;const ok=(c,l)=>{n++;if(!c){bad++;console.log("FAIL",l)}};
const call=async(m,p,b,tok)=>{const r=await h(new Request("http://x/api"+p,{method:m,headers:{"content-type":"application/json",...(tok?{authorization:"Bearer "+tok}:{})},body:b?JSON.stringify(b):undefined}));return r.json()};
const login=async e=>{const o=await call("POST","/otp",{email:e});return call("POST","/verify",{email:e,code:o.demo_code,country:"NG"})};
let hl=await call("GET","/health");ok(hl.database==="postgres"&&hl.auth==="better-auth","engines: "+JSON.stringify(hl));
for(const mode of ["both","body","header"]){globalThis.__BA_MODE=mode;const v=await login("m"+mode+"@x.com");
  ok(v.ok&&v.engine==="better-auth"&&!v.token.includes("."),"BA sign-in shape "+mode+": "+JSON.stringify(v).slice(0,90));
  ok((await call("GET","/bond/me","",v.token)).ok,"session validated ("+mode+")");
  ok((await call("GET","/bond/me","",v.token+".c2ln%3D")).ok,"signed form accepted ("+mode+")");}
globalThis.__BA_MODE="both";
ok(!(await call("GET","/bond/me","","forged")).ok,"forged token rejected");
let v=await login("out@x.com");await call("POST","/signout","",v.token);ok(!(await call("GET","/bond/me","",v.token)).ok,"sign-out revokes the session");
globalThis.__BA_MODE="orphan";v=await login("orph@x.com");ok(v.ok&&v.engine==="built-in","unvalidatable BA session -> built-in fallback");ok((await call("GET","/bond/me","",v.token)).ok,"fallback token works");
globalThis.__BA_MODE="throw";v=await login("thr@x.com");ok(v.ok&&v.engine==="built-in","BA throws -> built-in fallback");
globalThis.__BA_MODE="both";
const adm=(await login("admin@x.com")).token;
let ac=await call("GET","/authcheck","",adm);ok(ac.ok&&ac.steps.length>=6,"authcheck passes: "+JSON.stringify(ac.steps.filter(x=>!x.ok)));
ok((await call("GET","/authcheck","",(await login("nobody@x.com")).token)).error==="Admin access only.","authcheck is admin-only");
globalThis.__BA_MODE="throw";ac=await call("GET","/authcheck","",adm);ok(!ac.ok&&ac.steps.some(x=>!x.ok&&x.note),"authcheck reports the exact failing step");
ok(pgm.__store.size>3&&pgm.__log.some(q=>q.includes("select value from kv")),"data lives in postgres kv");
console.log(n+" checks, "+bad+" failed");
