process.env.GMAIL_USER="trex@gmail.com";process.env.GMAIL_APP_PASSWORD="abcd efgh ijkl mnop";process.env.ADMIN_EMAILS="admin@x.com";
import h from "./api.mjs";import nm from "nodemailer";
let n=0,bad=0;const ok=(c,l)=>{n++;if(!c){bad++;console.log("FAIL",l)}};
const call=async(m,p,b)=>(await h(new Request("http://x/api"+p,{method:m,headers:{"content-type":"application/json"},body:b?JSON.stringify(b):undefined}))).json();
const o=await call("POST","/otp",{email:"user@x.com"});
ok(o.ok&&o.email_sent&&!o.demo_code,"code emailed, never shown on screen");
const m=nm.__sent[0];ok(m&&m.to==="user@x.com"&&/Your Trex code is \d{6}/.test(m.text)&&m.user==="trex@gmail.com","Gmail message built correctly");
ok((await call("GET","/integrations")).email==="gmail","integrations reports gmail");
process.env.GMAIL_APP_PASSWORD="BAD";const f=await call("POST","/otp",{email:"u2@x.com"});ok(!f.ok&&!f.demo_code,"bad Gmail password -> clear error, no code leaked");
delete process.env.GMAIL_USER;delete process.env.GMAIL_APP_PASSWORD;
ok((await call("POST","/otp",{email:"admin@x.com"})).error?.includes("not set up"),"admin never gets on-screen code");
ok((await call("POST","/otp",{email:"user@x.com"})).demo_code,"preview only for normal users when no email set up");
console.log(n+" checks, "+bad+" failed");
